### ISSUE TITLE
Add the option to display the output in yaml/json format

### ISSUE THREAD

**Issue by garethjevans** [garethjevans/kubectl-permissions#24]
this would allow this plugin to used in script

**Comment by garethjevans** [comment]
flags should follow kubectl standards e.g. `-oyaml` or `--output=json`

**Comment by cagiti** [comment]
Assign this one to me if you want 😀

**Comment by cagiti** [comment]
How would you want it to look? Something like this or flatter?
```yaml
ServiceAccounts:
  sa-under-test:
    namespace: test-namespace
    ClusterRoleBindings:
      cluster-roles:
        ClusterRoles:
          cluster-level-role:
            apis:
              apps:
                deployments:
                  verbs:
                  - get
                  - watch
                  - list
                replicasets:
                  verbs:
                  - get
                  - watch
                  - list
    RoleBindings: ...
```

**Comment by garethjevans** [comment]
yeah, I like that.  or...

```yaml
serviceAccount: sa-under-test
  namespace: test-namespace
  clusterRoleBindings:
    - name: cluster-roles
      clusterRoles:
        - name: cluster-level-roles
          permissions:
            - apiGroups: apps
              resources:
                - deployments
                - replicasets
              verbs:
                - get
                - watch
                - list
            - apiGroups: core.k8s.io
              resources:
                - configmaps
                - pods
                - pods/log
                - services
              verbs:
                - get
                - watch
                - list
            - apiGroups: networking.k8s.io
              resources:
                - ingresses
              verbs:
                - get
```
