### ISSUE TITLE
Highlight invalid permissions

### ISSUE THREAD

**Issue by garethjevans** [garethjevans/kubectl-permissions#41]
If we're displaying a permission for a resource/group etc can we validate that that api actually exists? e.g. if I have a typo:

```
- apiGroups: ['tekton.io']
  resources:
  - taskruns
  - pipelineruns
  verbs: ['get', 'watch', 'list']
```

Can we show some how that `taskruns.tekton.io` is invalid?

Is it possible to determine that?
